apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
spec:
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
      - name: keycloak-app
        image: bitnami/keycloak
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_CREATE_ADMIN_USER
          value: "true"
        - name: KEYCLOAK_ADMIN_USER
          value: user
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: bitnami
        - name: KEYCLOAK_MANAGEMENT_USER
          value: manager
        - name: KEYCLOAK_MANAGEMENT_PASSWORD
          value: bitnami1
        - name: KEYCLOAK_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: keycloak-configmap
              key: database_host
        - name: KEYCLOAK_DATABASE_PORT
          value: "5432"
        - name: KEYCLOAK_DATABASE_NAME
          value: bitnami_keycloak
        - name: KEYCLOAK_DATABASE_USER
          value: bn_keycloak
        - name: KEYCLOAK_DATABASE_PASSWORD
          value: bn_keycloak
        - name: KEYCLOAK_DATABASE_SCHEMA
          value: public
        - name: KEYCLOAK_HTTP_PORT
          value: "8080"
        - name: KEYCLOAK_HTTPS_PORT
          value: "8443"
        - name: KEYCLOAK_BIND_ADDRESS
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-app-service
spec:
  selector:
    app: keycloak-app
  ports:
  - port: 8080
    targetPort: 8080